version: '3'

services:
  todosDB:
    image: postgres:15.3
    container_name: teslo-shop-next
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgresvolnext:/var/lib/postgresql/data

volumes:
  postgresvolnext:


networks:
  nextwork:
    driver: bridge
